name: HTML CI with HTMLHint

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시되었을 때 동작합니다.
  pull_request:
    branches:
      - main  # 메인 브랜치로의 PR에서 동작합니다.

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # 현재 저장소를 체크아웃합니다.

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"  # 사용할 Node.js 버전

    - name: Install HTMLHint
      run: |
        npm install -g htmlhint@1

    - name: Run HTMLHint
      run: |
        htmlhint "**/*.html"
